### ISSUE TITLE
ds.merge.o call causes server side error

### ISSUE THREAD

**Issue by StuartWheater** [datashield/dsBetaTestClient#109]
The following call, generates the following message ``argument is of length zero``
~~~~
res <- ds.merge.o(x.name="test_1_df", y.name="test_2_df", by.x.names="LAB_TSC", by.y.names="LAB_TRIG", newobj="merge_newobj")
~~~~
the setup before the call is
~~~~
spec_vectors_1 <- c('D$LAB_TSC', 'D$LAB_HDL')
spec_vectors_2 <- c('D$LAB_TRIG', 'D$DIS_AMI')
ds.dataFrame.o(x=spec_vectors_1, newobj="test_1_df")
ds.dataFrame.o(x=spec_vectors_2, newobj="test_2_df")``
~~~~
in the Opal server's logs there is the following message: 
~~~~
2019-07-04 07:08:35,902 [R Operations Consumer org.obiba.opal.r.service.OpalRSession$RCommandsConsumer@6e6df872] ERROR org.obiba.opal.r.service.OpalRSession - Error when consuming R command: Error while evaluating 'is.null(base::assign('merge_newobj', value={dsBetaTest::mergeDS.o( "test_1_df","test_2_df","LAB_TSC","LAB_TRIG",FALSE,FALSE,TRUE,".x,.y",TRUE,NULL )}))' -> Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

org.obiba.opal.spi.r.REvaluationRuntimeException: Error while evaluating 'is.null(base::assign('merge_newobj', value={dsBetaTest::mergeDS.o( "test_1_df","test_2_df","LAB_TSC","LAB_TRIG",FALSE,FALSE ,TRUE,".x,.y",TRUE,NULL )}))' -> Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column
        at org.obiba.opal.spi.r.AbstractROperation.eval(AbstractROperation.java:123) ~[opal-spi-r-2.14.1.jar:na]
        at org.obiba.opal.spi.r.AbstractROperationWithResult.eval(AbstractROperationWithResult.java:68) ~[opal-spi-r-2.14.1.jar:na]
        at org.obiba.opal.spi.r.AbstractROperation.eval(AbstractROperation.java:96) ~[opal-spi-r-2.14.1.jar:na]
        at org.obiba.opal.spi.r.AbstractROperationWithResult.eval(AbstractROperationWithResult.java:63) ~[opal-spi-r-2.14.1.jar:na]
        at org.obiba.opal.datashield.RestrictedAssignmentROperation.doWithConnection(RestrictedAssignmentROperation.java:42) ~[opal-datashield-2.14.1.jar:na]
        at org.obiba.opal.spi.r.AbstractROperation.doWithConnection(AbstractROperation.java:236) ~[opal-spi-r-2.14.1.jar:na]
        at org.obiba.opal.r.service.OpalRSession.execute(OpalRSession.java:186) ~[opal-r-2.14.1.jar:na]
        at org.obiba.opal.r.service.OpalRSession$RCommandsConsumer.consume(OpalRSession.java:372) [opal-r-2.14.1.jar:na]
        at org.obiba.opal.r.service.OpalRSession$RCommandsConsumer.run(OpalRSession.java:360) [opal-r-2.14.1.jar:na]
        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120) [shiro-core-1.4.0.jar:1.4.0]
        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108) [shiro-core-1.4.0.jar:1.4.0]
        at org.obiba.opal.core.tx.TransactionalThread$1.doInTransactionWithoutResult(TransactionalThread.java:35) [opal-core-2.14.1.jar:na]
        at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34) [spring-tx-4.3.19.RELEASE.jar:4.3.19.RELEASE]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.3.19.RELEASE.jar:4.3.19.RELEASE]
        at org.obiba.opal.core.tx.TransactionalThread.run(TransactionalThread.java:32) [opal-core-2.14.1.jar:na]
~~~~

**Comment by davraam** [comment]
Hi Stuart,

The names of the variables in the two new dataframes 'test_1_df' and 'test_2_df' include the dollar sign and the name of the initial dataset. So we have to use the correct names in the ds.merge.o function.

So the following should not fail:

spec_vectors_1 <- c('LD$LAB_TSC', 'LD$LAB_HDL')
spec_vectors_2 <- c('LD$LAB_TRIG', 'LD$DIS_AMI')
ds.dataFrame.o(x=spec_vectors_1, newobj="test_1_df")
ds.dataFrame.o(x=spec_vectors_2, newobj="test_2_df")

res <- ds.merge.o(x.name="test_1_df", y.name="test_2_df", by.x.names="**LD$**LAB_TSC", by.y.names="**LD$**LAB_TRIG", newobj="merge_newobj")
